name: "Static Analysis"

on:
  pull_request:
    paths:
      - composer.*
      - lib/**
      - phpstan*
      - psalm*
  push:
    paths:
      - composer.*
      - lib/**
      - phpstan*
      - psalm*

jobs:
  static-analysis-phpstan:
    name: Static Analysis PHPStan
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: '8.2'
          tools: cs2pr

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Static Analysis (PHPStan)
        run: "vendor/bin/phpstan analyse --error-format=checkstyle | cs2pr"

  static-analysis-psalm:
    name: Static Analysis Psalm
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        uses: ramsey/composer-install@v2

      - name: Static Analysis (PHPStan)
        run: "vendor/bin/psalm --shepherd"
